name: New Data Reference Standard Proposal
description: Propose a new DRS
title: "[DRS PROPOSAL]: "
labels: DRS
body:
  - type: textarea
    id: desc
    attributes:
      label: "describe the Proposal"
      description: "Describe the proposed reference standard"
    validations:
      required: true
  - type: checkboxes
  id: type
  attributes:
    label: Proposed Structure
    description: You may select more than one.
    options:
      - label: codelist
        required: true
      - label: **schema**
      - label: ontology
      - label: taxonomy
  - type: textarea
    id: additional
    attributes:
      label: "Additional Info"
      description: "Add any other context about the change here."
    validations:
      required: false
