name: Scrape Website

on:
  schedule:
    - cron: '0 12 * * *' 
  workflow_dispatch:
  
jobs:
  scrape_job:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'  # Use the version of Python you need

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests beautifulsoup4

    - name: Run scraper
      run: python scrape-main-page.py

    - name: Commit and Push Result
      run: |
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        git config --global user.name 'github-actions[bot]'
        git add scraped_table_en.csv scraped_table_fr.csv
        git commit --allow-empty -m "Update scraped table data"
        git push
